experiment_name: "InstructMistral0.2"
run_name: "deu_fr_corrected_bleu"
use_context: False
separateur_context: "\n"
version: 1
llm_model: "artifacts/TowerInstruct-Mistral-7B-v0.2"
model_type : "tower"
prompt: "config/prompts/prompt_v1.yml"
batch_size: 100
max_token: 500
device: 0 #1 or 0 or "cpu"
src_code: "deu_Latn"
src_name: "German"
tgt_code: "fra_Latn"
tgt_name: "French"
ignore_prompt: ["\n", "", " "]